trigger:
  - main

resources:
  - repo: self

# use library variables
variables:
  - group: "CICD"
  - name: app_var
    value: $[variables.appVariable]
parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "public-api"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool: test

        steps:
          - script: |
              echo "var=$(app_var)"
              echo "tag= ${{ parameters.tag }}"

          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              containerRegistry: 'registry'
              repository: ${{ parameters.imageName }}
              dockerfile: "**/qa.dockerfile"
              tags: |
                ${{ parameters.tag }}
              arguments: '--build-arg APP_ENV=$(app_var)'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: 'push'
              containerRegistry: 'registry'
              repository: ${{ parameters.imageName }}
              tags: |
                ${{ parameters.tag }}

      - job: Deploy
        displayName: Deploy
        dependsOn: Build
        pool: test
        steps:
          - script: echo "Deploying..."
          - task: AzureContainerApps@1

            inputs:
              azureSubscription: 'appDeployConnection'
              imageToDeploy: acrapps.azurecr.io/public-api:$(Build.BuildId)

              containerAppName: 'public-api'
              resourceGroup: 'rg-cachac'

              acrUsername: 'acrapps'
              acrPassword: 'XXX'
